### PR TITLE
Minor style consistency fixes

### PR DESCRIPTION
**Pull request by shamsher31**
Minor style consistency fixes if you are planing for minification and writing test cases in future.

### CODE REVIEW

**Comment by shamsher31** [comment]
I have downloaded Android app from app store. If Im online I can see add on bottom of the app. But if Im gone offline I still see black box at the bottom of the app. This appears to be problem when you updated app to Ionic.

**Comment by paulomcnally** [comment]
@shamsher31 have screenshot?

**Comment by shamsher31** [comment]
Device:  Moto E and Android 4.4

**Comment by paulomcnally** [comment]
Use a Pro version or Free version?

**Comment by shamsher31** [comment]
Free Version, but when I had a previous free version, bottom block was not visible when offline.

**Comment by paulomcnally** [comment]
@shamsher31 please update you're application from google play.

**Pull request merged**
